# Numpy

## Create a NumPy ndarray Object

In [1]:
import numpy as np

# list
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>



- ndarray ย่อมาจาก N-dimensional array หรือ อาร์เรย์ N มิติ

In [60]:
import numpy as np

# tuple
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## NumPy Data Types

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [61]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [64]:
# Creating Arrays With a Defined Data Type
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [63]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

## Dimensions in Arrays

In [67]:
import numpy as np

arr = np.array(42)

print(arr)
print(arr.ndim)  # Number of dimensions

42
0


In [68]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)  # Number of dimensions

[1 2 3 4 5]
1


In [69]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)  # Number of dimensions

[[1 2 3]
 [4 5 6]]
2


In [70]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim)  # Number of dimensions

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[6, 5, 4], [3, 2, 1]]])
arr[0,0,0]

np.int64(6)

In [ ]:
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  [6 5 4]


## Slicing arrays

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[1 2 3 4 5]


# NumPy Array Copy vs View

In [77]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [78]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [79]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [80]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
z = arr

print("x.base:", x.base)
print("y.base:", y.base)
print("z.base:", z.base)

#print address. in memory of x,y,z
print('\nAddress in memory of arr:', id(arr))
print('Address in memory of x:', id(x))
print('Address in memory of y:', id(y))
print('Address in memory of z:', id(z))

x.base: None
y.base: [1 2 3 4 5]
z.base: None

Address in memory of arr: 4487686512
Address in memory of x: 4487686608
Address in memory of y: 4487686704
Address in memory of z: 4487686512


## NumPy Array Shape

In [86]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

## NumPy Array Reshaping

In [89]:
import numpy as np
#1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [90]:
import numpy as np
# 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Reference: https://www.w3schools.com/python/numpy/default.asp